### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by jilner** [leftthomas/SuperResolution#11] opened 2019-03-04 03:43 UTC
Firstly thanks for you work
When ues python3 load the  epoch_3_100.pt, it comes  _pickle.UnpicklingError: invalid load key, '\xef'.
How can i  reslove this problem  ?

**Comment by leftthomas** [comment] 2019-03-04 13:08
Duplicate of #6

**Closed as completed by leftthomas** 2019-03-04 13:08 UTC
