### ISSUE TITLE
on-hand model availability

### ISSUE THREAD

**Issue by ljz1998zzzz** [leftthomas/SuperResolution#48] opened 2023-04-24 10:00 UTC
Hello:

This work is wonderful and I wonder if I could get an on-hand trained model for this work. This will help me a lot. Thanks.

**Comment by leftthomas** [comment] 2023-04-24 11:28
@ljz1998zzzz 
Duplicate of #25

**Closed as completed by leftthomas** 2023-04-24 11:28 UTC

**Comment by ljz1998zzzz** [comment] 2023-04-24 11:47
My carelessness.
